name: CMake

on: [push]

env:
  CXX: g++
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Recursively clone aegis.cpp
      run: git clone --recursive https://github.com/zeroxs/aegis.cpp
    - name: Install aegis.cpp dependencies
      working-directory: ${{github.workspace}}/aegis.cpp
      run: CXX=$CXX sudo bash ./install-deps.sh
    - name: Install aegis.cpp to system
      working-directory: ${{github.workspace}}/aegis.cpp
      run: mkdir -p build && cd build && CXX=$CXX cmake -DCMAKE_CXX_STANDARD=17 .. && make -j1 && sudo make install
    - name: Test project build
      run: mkdir -p build && cd build && CXX=$CXX cmake .. && make -j1
    - name: Show file information
      working-directory: ${{github.workspace}}/bin
      run: ls -l
